# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

matrix:
  include:
    - r: oldrel
    - r: release
    - r: devel
    - os: osx
